# NumPy模块

1. 数组对象ndarray

In [1]:
#导入numpy库
import numpy as np 
arr1=np.array([1,2,3,4,5])#创建一维数组
print("一维数组:",arr1)

一维数组: [1 2 3 4 5]


In [2]:
#创建二维数组
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
#常用属性
print("arr2的维数",arr2.ndim)
print("arr1的形状:",arr1.shape,"\tarr2的形状:",arr2.shape)
print("arr1的元素类型为:",arr1.dtype,"\tarr2的元素类型为:",arr2.dtype)
print("arr1的数组个数:",arr1.size,"\tarr2的元素个数:",arr2.size)
print("arr1的数组空间",arr1.itemsize)
#修改数组形状
arr2.shape=4,3
print(arr2)

arr2的维数 2
arr1的形状: (5,) 	arr2的形状: (3, 4)
arr1的元素类型为: int32 	arr2的元素类型为: int32
arr1的数组个数: 5 	arr2的元素个数: 12
arr1的数组空间 4
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
#使用arange创建数组,默认步长为1
print(np.arange(5))
print(np.arange(0,5))
print(np.arange(0,6,2))

[0 1 2 3 4]
[0 1 2 3 4]
[0 2 4]


In [5]:
# 使用linspace创建,默认个数50
print(np.linspace(1,50))
print(np.linspace(1,10,20))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [6]:
#使用logspace创建等比数组,同上
print(np.logspace(1,50))
print(np.logspace(1,10,10))

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10
 1.e+11 1.e+12 1.e+13 1.e+14 1.e+15 1.e+16 1.e+17 1.e+18 1.e+19 1.e+20
 1.e+21 1.e+22 1.e+23 1.e+24 1.e+25 1.e+26 1.e+27 1.e+28 1.e+29 1.e+30
 1.e+31 1.e+32 1.e+33 1.e+34 1.e+35 1.e+36 1.e+37 1.e+38 1.e+39 1.e+40
 1.e+41 1.e+42 1.e+43 1.e+44 1.e+45 1.e+46 1.e+47 1.e+48 1.e+49 1.e+50]
[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]


In [7]:
#创建其他数组
print(np.zeros(5))#0填充数组
print(np.zeros((2, 3)))
print(np.ones((3,3)))#1填充数组
print(np.eye(4))#主对角线为1的数组
print(np.diag([3,5,2,1]))#自定义主对角线的数组
print(np.ones((3,3)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[3 0 0 0]
 [0 5 0 0]
 [0 0 2 0]
 [0 0 0 1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#索引与切片
print(arr1)
print("索引1的元素:",arr1[1])
print("切片[:3]",arr1[:3])
print("切片[3:]",arr1[3:])
print("切片[:]",arr1[:])
print("切片[1:5]",arr1[1:5:2])

print(arr2)
print("索引[2,1]的元素",arr2[2][1])
print("切片[0,:]",arr2[0,:])
print("切片[:,0]",arr2[:,0])
print("切片[2:3,1:2]",arr2[2:3,1:2])
#使用整数数组索引
print(arr2)
# [arr2[0,0],arr[1,1],arr2[2,0]]依次对应
print("整数索引[[0,0],[1,1],[2,0]]依次对应:",arr2[[0,1,2],[0,1,0]])
print("整数索引[[[0,0],[0,2]],[[3,0],[3,2]]]:\n",arr2[np.array([[0,0],[3,3]]),np.array([[0,2],[0,2]])])
print("整数索引:\n",arr2[:1,(0,1,0)])

#使用布尔索引
print(arr2)
print("布尔索引:",arr2[arr2>3])

[1 2 3 4 5]
索引1的元素: 2
切片[:3] [1 2 3]
切片[3:] [4 5]
切片[:] [1 2 3 4 5]
切片[1:5] [2 4]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
索引[2,1]的元素 8
切片[0,:] [1 2 3]
切片[:,0] [ 1  4  7 10]
切片[2:3,1:2] [[8]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
整数索引[[0,0],[1,1],[2,0]]依次对应: [1 5 7]
整数索引[[[0,0],[0,2]],[[3,0],[3,2]]]:
 [[ 1  3]
 [10 12]]
整数索引:
 [[1 2 1]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
布尔索引: [ 4  5  6  7  8  9 10 11 12]


In [9]:
#变换数组形态  
arr1=np.arange(5)
print("原数组",arr1)
print("临时改变数组形状:\n",arr1.reshape([5,1]))#临时改变
print("reshape后的原数组",arr1)
# #永久修改原数组形状
arr1.shape=[5,1]
print("使用shape属性永久修改数组形状:\n",arr1)
#数组展平
print(arr2)
print("数组展平ravel:",arr2.ravel())
print("数组竖着展平flatten::",arr2.flatten("F"))
print("数组横着展平flatten::",arr2.flatten())
#数组组合
arr3=np.arange(12).reshape(3,4)
arr4=arr3*2
print("原数组arr3和arr4分别为:\n",arr3,"\n\n",arr4)
print("横向组合为:\n",np.hstack((arr3,arr4)))
print("横向向组合为:\n",np.concatenate((arr3,arr4),axis=1))

print("纵向组合为:\n",np.vstack((arr3,arr4)))
print("纵向组合为:\n",np.concatenate((arr3,arr4),axis=0))

#数组分割
arr5=np.arange(16).reshape(4,4)
print("原数组:\n",arr5)
print("横向分割:\n",np.hsplit(arr5,2))
print("横向分割:\n",np.split(arr5,2,axis=1))
print("纵向分割:\n",np.vsplit(arr5,2))
print("纵向分割:\n",np.split(arr5,2,axis=0))

原数组 [0 1 2 3 4]
临时改变数组形状:
 [[0]
 [1]
 [2]
 [3]
 [4]]
reshape后的原数组 [0 1 2 3 4]
使用shape属性永久修改数组形状:
 [[0]
 [1]
 [2]
 [3]
 [4]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
数组展平ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12]
数组竖着展平flatten:: [ 1  4  7 10  2  5  8 11  3  6  9 12]
数组横着展平flatten:: [ 1  2  3  4  5  6  7  8  9 10 11 12]
原数组arr3和arr4分别为:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
横向组合为:
 [[ 0  1  2  3  0  2  4  6]
 [ 4  5  6  7  8 10 12 14]
 [ 8  9 10 11 16 18 20 22]]
横向向组合为:
 [[ 0  1  2  3  0  2  4  6]
 [ 4  5  6  7  8 10 12 14]
 [ 8  9 10 11 16 18 20 22]]
纵向组合为:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
纵向组合为:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
原数组:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
横向分割:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],

2. 随机数

In [10]:
np.random.seed(0)#随机数种子,随机数种子相同,则生成的随机数也相同
print(np.random.random(5))#生成5个随机数
print(np.random.rand())#生成均匀分布的单个浮点数
print(np.random.rand(2,2))#生成均匀分布(2,2)浮点数
print(np.random.randint(1,10,size=[10,10]))#生成[1,10)的[10,10]个随机数

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
0.6458941130666561
[[0.43758721 0.891773  ]
 [0.96366276 0.38344152]]
[[7 8 8 9 2 6 9 5 4 1]
 [4 6 1 3 4 9 2 4 4 4]
 [8 1 2 1 5 8 4 3 8 3]
 [1 1 5 6 6 7 9 5 2 5]
 [9 2 2 8 4 7 8 3 1 4]
 [6 5 5 7 5 5 4 5 5 9]
 [5 4 8 6 6 1 2 6 4 1]
 [6 1 2 3 5 3 1 4 3 1]
 [8 6 1 3 8 3 3 4 4 3]
 [4 5 2 3 2 5 7 9 3 4]]


3. NumPy矩阵与通用函数

In [11]:
#矩阵是ndarray的子类
import numpy as np
#创建矩阵:使用mat与matrix
matr1=np.mat("1 2 3;4 5 6;7 8 9")
matr2=np.matrix([[11,22,33],[44,55,66],[77,88,99]])
print("mat,matrix创建的矩阵为:",matr1,matr2,sep="\n")
# 使用bmat创建矩阵
arr1=np.eye(3)
arr2=arr1*3
print("两个中间变量数组:",arr1,arr2,sep="\n")
matr3=np.bmat('arr1 arr2;arr1 arr2')
print("用bmat和arr1,arr2组合数组创建矩阵:",matr3,sep="\n")



mat,matrix创建的矩阵为:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]
两个中间变量数组:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]
用bmat和arr1,arr2组合数组创建矩阵:
[[1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]
 [1. 0. 0. 3. 0. 0.]
 [0. 1. 0. 0. 3. 0.]
 [0. 0. 1. 0. 0. 3.]]


In [12]:
#矩阵的运算
print("原:",matr1,matr2,sep="\n")
print("相加:",matr1+matr2,sep="\n")
print("相减:",matr1-matr2,sep="\n")
print("数乘:",matr1*10,sep="\n")
print("相乘:",matr1*matr2,sep="\n")
print("原:",matr1,sep="\n")
print("转置",matr1.T,sep="\n")
print("共轭转置",matr1.H,sep="\n")
print("逆矩阵",matr1.I,sep="\n")
print("二维数组视图",matr1.A,sep="\n")

原:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]
相加:
[[ 12  24  36]
 [ 48  60  72]
 [ 84  96 108]]
相减:
[[-10 -20 -30]
 [-40 -50 -60]
 [-70 -80 -90]]
数乘:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
相乘:
[[ 330  396  462]
 [ 726  891 1056]
 [1122 1386 1650]]
原:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
转置
[[1 4 7]
 [2 5 8]
 [3 6 9]]
共轭转置
[[1 4 7]
 [2 5 8]
 [3 6 9]]
逆矩阵
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
二维数组视图
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
#ufunc函数
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,1],[1,2,1]])
print("原数组:",arr1,arr2,sep="\n")
print("相加:",arr1+arr2,sep="\n")
print("相减:",arr1-arr2,sep="\n")
print("相乘:",arr1*arr2,sep="\n")
print("相除:",arr1/arr2,sep="\n")
print("幂运算:",arr1**arr2,sep="\n")
print(">:",arr1>arr2,sep="\n")
print(">=:",arr1>=arr2,sep="\n")
print("<:",arr1<arr2,sep="\n")
print("<=:",arr1<=arr2,sep="\n")
print("!=:",arr1!=arr2,sep="\n")
print("all!=:",np.all(arr1!=arr2),sep="\n")
print("any!=:",np.any(arr1!=arr2),sep="\n")

原数组:
[[1 2 3]
 [4 5 6]]
[[1 2 1]
 [1 2 1]]
相加:
[[2 4 4]
 [5 7 7]]
相减:
[[0 0 2]
 [3 3 5]]
相乘:
[[ 1  4  3]
 [ 4 10  6]]
相除:
[[1.  1.  3. ]
 [4.  2.5 6. ]]
幂运算:
[[ 1  4  3]
 [ 4 25  6]]
>:
[[False False  True]
 [ True  True  True]]
>=:
[[ True  True  True]
 [ True  True  True]]
<:
[[False False False]
 [False False False]]
<=:
[[ True  True False]
 [False False False]]
!=:
[[False False  True]
 [ True  True  True]]
all!=:
False
any!=:
True


4. NumPy统计分析

In [14]:
import numpy as np
#写二进制文件
arr1=np.arange(50).reshape(5,10)
arr2=arr1*10
# arr2=np.arange(50).reshape(10,15)
print("数组数据:",arr1,arr2,sep="\n")
np.save("./save_arr1",arr1)#存储单个数组
np.savez("./save_arr1_arr2",arr1,arr2)#存储多个数组

#读二进制文件
print("读取到的单个数组数据:",np.load("./save_arr1.npy"),sep="\n")
print("读取到的多个数组数据:",np.load("./save_arr1_arr2.npz")["arr_0"],np.load("./save_arr1_arr2.npz")["arr_1"],sep="\n")

#读写文本文件
np.savetxt("./arr1.txt",arr1,fmt="%d",delimiter=",")

print("loadtxt读:\n",np.loadtxt("./arr1.txt",delimiter=","))
print("genfromtxt读:\n",np.genfromtxt("./arr1.txt",delimiter=","))


数组数据:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[  0  10  20  30  40  50  60  70  80  90]
 [100 110 120 130 140 150 160 170 180 190]
 [200 210 220 230 240 250 260 270 280 290]
 [300 310 320 330 340 350 360 370 380 390]
 [400 410 420 430 440 450 460 470 480 490]]
读取到的单个数组数据:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
读取到的多个数组数据:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[  0  10  20  30  40  50  60  70  80  90]
 [100 110 120 130 140 150 160 170 180 190]
 [200 210 220 230 240 250 260 270 280 290]
 [300 310 320 330 340 350 360 370 380 390]
 [400 410 420 430 440 450 460 470 480 490]]
loadtxt读:
 [[ 0.  1.  2.  3.  4.  5.  6.

In [15]:
#1.直接排序排序
#reverse = True 降序， reverse = False 升序（默认）
arr3=np.random.randint(1,10,15)
print(f"生成的随机数组为:{arr3}")
arr3.sort()
print(f"直接排序:{arr3}")

arr4=np.random.randint(10,50,15).reshape(3,5)
print(f"生成的随机数组为:\n{arr4}")
arr4.sort(axis=1)
print(f"横轴排序:\n{arr4}")
arr4.sort(axis=0)
print(f"纵轴排序:\n{arr4}")

#argsort排序
arr5=np.random.randint(1,100,10)
print(f"生成的随机数组为:{arr5}")
print(f"排序后索引:{arr5.argsort()}")

#lexsort排序
a=np.array([3,2,6,4,5])
b=np.array([50,30,40,20,10])
c=np.array([400,300,600,100,200])
d=np.lexsort((a,b,c))
print(f"我不理解:{d}")

生成的随机数组为:[1 1 7 1 7 4 4 9 9 9 3 4 3 1 9]
直接排序:[1 1 1 1 3 3 4 4 4 7 7 9 9 9 9]
生成的随机数组为:
[[18 29 41 18 36]
 [12 13 24 42 14]
 [13 21 32 23 21]]
横轴排序:
[[18 18 29 36 41]
 [12 13 14 24 42]
 [13 21 21 23 32]]
纵轴排序:
[[12 13 14 23 32]
 [13 18 21 24 41]
 [18 21 29 36 42]]
生成的随机数组为:[57 17 25 30 22 26 81 61 62 84]
排序后索引:[1 4 2 5 3 0 7 8 6 9]
我不理解:[3 4 1 0 2]


In [16]:
#2.去重与重复数据
#数据去重
arr6=np.random.randint(1,10,15)
print(f"原始数据:{arr6}")
print(f"去重并排序np.unique:{np.unique(arr6)}")
print(f"去重排序sorted(set()):{sorted(set(arr6))}")

#重复数据
arr7=np.array([1,2,3])
print(f"原始数据:{arr7}")
print(f"重复后的数据为:{np.tile(arr7,3)}")
arr8=np.arange(9).reshape(3,3)
print(f"原始数据:\n{arr8}")
print(f"横向重复:\n{arr8.repeat(3,axis=1)}")
print(f"竖向重复:\n{arr8.repeat(3,axis=0)}")

原始数据:[2 9 1 5 7 6 8 9 9 3 9 7 7 2 7]
去重并排序np.unique:[1 2 3 5 6 7 8 9]
去重排序sorted(set()):[1, 2, 3, 5, 6, 7, 8, 9]
原始数据:[1 2 3]
重复后的数据为:[1 2 3 1 2 3 1 2 3]
原始数据:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
横向重复:
[[0 0 0 1 1 1 2 2 2]
 [3 3 3 4 4 4 5 5 5]
 [6 6 6 7 7 7 8 8 8]]
竖向重复:
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [3 4 5]
 [3 4 5]
 [3 4 5]
 [6 7 8]
 [6 7 8]
 [6 7 8]]


In [17]:
#常用统计函数
arr9=np.arange(12).reshape(3,4)
print(f"原数据:\n{arr9}")
print(f"数组求和:{np.sum(arr9)}")
print(f"横轴求和:{arr9.sum(axis=1)}")
print(f"纵轴求和:{arr9.sum(axis=0)}")
print(f"数组均值:{np.mean(arr9)}")
print(f"横轴平均:{arr9.mean(axis=1)}")
print(f"纵轴平均:{arr9.mean(axis=0)}")
print(f"数组标准差:{np.std(arr9)}")
print(f"数组方差:{np.var(arr9)}")
print(f"数组最小:{np.min(arr9)}")
print(f"数组最大:{np.max(arr9)}")
print(f"最小索引:{np.argmin(arr9)}")
print(f"最大索引:{np.argmax(arr9)}")
print(f"中间求和:{np.cumsum(arr9)}")
print(f"中间求积:{np.cumprod(np.array([1,2,3,4,5]))}")

原数据:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
数组求和:66
横轴求和:[ 6 22 38]
纵轴求和:[12 15 18 21]
数组均值:5.5
横轴平均:[1.5 5.5 9.5]
纵轴平均:[4. 5. 6. 7.]
数组标准差:3.452052529534663
数组方差:11.916666666666666
数组最小:0
数组最大:11
最小索引:0
最大索引:11
中间求和:[ 0  1  3  6 10 15 21 28 36 45 55 66]
中间求积:[  1   2   6  24 120]


## 上课笔记

In [24]:
import numpy as np
# 创建numpy数组
'''
Ndim：返回int，表示数组的维数
Shape：返回tuple，表示数组形状的阵列，对于n行m列的矩阵，形状为(n,m)
Size：返回int，表示数组的元素总数，等于数组形状的乘积
Dtype：返回data-type，表示数组中元素的数据类型
Itemsize：返回int，表示数组的每个元素的大小（以字节为单位），例如，一个元素类型为float64的数组的itemsiz属性值为8（float64占用64个bits，每个字节长度为8，所以64/8，占用8个字节），一个元素类型为complex32的数组的itemsiz属性值为4，即32/8

在实际的业务数据处理中，为了更准确地计算结果，需要使用不同精度的数据类型。
NumPy极大程度地扩充了原生Python的数据类型。
在NumPy中，所有数组的数据类型是同质的，即数组中的所有元素类型必须是一致的。
将元素类型保持一致可以更容易确定该数组所需要的存储空间。
int8、uint8 | i1、u1 | 有符号和无符号的8位整数（1个字节）
int16、uint16 | i2、u2 |有符号和无符号的16位整数（2个字节）
int32、uint32 |i4、u4 |有符号和无符号的32位整数（4个字节）
int64、uint64 |i8、u8 |有符号和无符号的64位整数（8个字节）
float16 |f2 |半精度浮点数(16位)
bool_	布尔型数据类型（True 或者 False）
float32 |f4或f |标准单精度浮点数(32位)
float64 |f8或d |标准双精度浮点数(64位)
Float128 |F16或g |扩展精度浮点数
complex64 |c8 |复数，分别用两个32位浮点数表示实部和虚部
complex128 |c16 |复数，分别用两个64位浮点数表示实部和虚部
object | O | Python对象类型
string_ |S |固定长度字符串类型(每个字符1字节,长度为10则是S10）
unicode |U |固定长度的unicode类型
'''
# np.array(Object数组对象,Dtype=None数据类型,Ndime=0维度)
# Object：接收array_like，表示所需创建的数组对象，无默认值
# Dtype：接收data-type，表示数组所需的数据类型，如果未给定，那么选择保存对象所需的最小类型，默认为None
# Ndmin：接收int，表示指定生成数组应该具有的最小维数，默认为0

array1=np.array((1,2,3,4,5))
print(f"\n数组:{array1}\n类型:{type(array1)}\n维度{array1.ndim}\n形状{array1.shape}")
print(f"占用字节:{array1.itemsize}\n元素数据类型:{array1.dtype}\n长度{array1.size}")

array1=np.array("123")
print(f"\n数组:{array1}\n类型:{type(array1)}\n维度{array1.ndim}\n形状{array1.shape}")
print(f"占用字节:{array1.itemsize}\n元素数据类型:{array1.dtype}\n长度{array1.size}")


# array1=np.arange(1,7).reshape(3,2)
array1=np.array(([1,2],[3.1,4],[5,6]))
print(f"\n数组:\n{array1}\n类型:{type(array1)}\n维度{array1.ndim}\n形状{array1.shape}")
print(f"占用字节:{array1.itemsize}\n元素数据类型:{array1.dtype}\n长度{array1.size}")
# array1=np.arange(1,7).reshape(3,2)

array1=np.array(([1,2],[3.1,4],[5,"6"]))
print(f"\n数组:\n{array1}\n类型:{type(array1)}\n维度{array1.ndim}\n形状{array1.shape}")
print(f"占用字节:{array1.itemsize}\n元素数据类型:{array1.dtype}\n长度{array1.size}")
# array1=np.arange(1,7).reshape(3,2)
array1=np.array(([1,2],[3.1,4],[5,6]),dtype="U")
print(f"\n数组:\n{array1}\n类型:{type(array1)}\n维度{array1.ndim}\n形状{array1.shape}")
print(f"占用字节:{array1.itemsize}\n元素数据类型:{array1.dtype}\n长度{array1.size}")
# array1=np.arange(1,7).reshape(3,2)

#创建多维度数组
#维度ndmin参数会升高但不会降低
array1=np.array([1,2,3,4,5,6,3],ndmin=6)
print(array1)
array1=np.array(([[1,2],[3,4],[5,6]]),ndmin=1)
print(array1)



数组:[1 2 3 4 5]
类型:<class 'numpy.ndarray'>
维度1
形状(5,)
占用字节:4
元素数据类型:int32
长度5

数组:123
类型:<class 'numpy.ndarray'>
维度0
形状()
占用字节:12
元素数据类型:<U3
长度1

数组:
[[1.  2. ]
 [3.1 4. ]
 [5.  6. ]]
类型:<class 'numpy.ndarray'>
维度2
形状(3, 2)
占用字节:8
元素数据类型:float64
长度6

数组:
[['1' '2']
 ['3.1' '4']
 ['5' '6']]
类型:<class 'numpy.ndarray'>
维度2
形状(3, 2)
占用字节:128
元素数据类型:<U32
长度6

数组:
[['1' '2']
 ['3.1' '4']
 ['5' '6']]
类型:<class 'numpy.ndarray'>
维度2
形状(3, 2)
占用字节:12
元素数据类型:<U3
长度6
[[[[[[1 2 3 4 5 6 3]]]]]]
[[1 2]
 [3 4]
 [5 6]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [33]:
#生成数组
import numpy as np
#创建等差数列:agange(起始,终值,步长)
"""
numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
通过指定开始值、终值和步长来创建一维数组，创建的数组不含终值。
start 接收int或实数，表示数组的开始值，生成的区间包括该值，默认为0
stop 接收int或实数，表示数组的终值，生成的区间不包括该值，无默认值
step 接收int或实数，表示在数组中，值之间的间距，默认为1
dtype 接收数据类型，表示输出数组的类型，默认为None
"""

arr1=np.arange(0,-101,-5)
print(arr1)

# 使用linspace创建等差数列,默认个数50
"""numpy.linspace(start, stop, num=50, endpoint=Truee, retstep=False, dtype=None, axis=0)
endpoint=True,默认包含stop
linspace函数通过指定开始值、终值和元素个数来创建一维数组，默认设置包括终值

start 接收array_like，表示起始值，无默认值
stop 接收array_like，表示结束值，无默认值
num 接收int，表示生成的样本数，默认为50
dtype 接收数据类型，表示输出数组的类型，默认为None
"""
print(np.linspace(0,100,20))






#使用logspace创建等比数组,默认50个
# 10的start方开始
# 10的stop方结束
"""
numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
logspace函数和linspace函数类似，它创建的是等比数列
start 接收array_like，表示起始值，无默认值
stop 接收array_like，表示结束值，无默认值
num 接收int，表示生成的样本数，默认为50
dtype 接收数据类型，表示输出数组的类型，默认为None
base=10.0 基数 默认10.0

"""
# print(np.logspace(1,2,base=10.0))
print(np.logspace(0,10,11,base=2.0))


#创建其他数组
"""

（2）numpy.identity()
numpy.identity()函数用于创建一个n*n的单位矩阵数组（主对角线元素全为1，其余位置全为0）

numpy.identity(n, dtype=None)

n：int型，指定数组的行和列。

"""
print("np.identit\n",np.identity(4))#主对角线为1的,其他位置为0的矩阵数组
print()

"""
numpy.eye()函数返回一个二维数组，对角线为1，其他地方为0。

对角线可以是主、上或下，这取决于可选参数k。正k用于上对角线，负k用于下对角线，0 k(默认)用于主对角线

numpy.eye(N, M=None, k=0, dtype=float, order='C')
N：int型，表示数组的行数
M：int型，可选项，数组的列数，默认为N
k：int型，可选项，对角线的下标，默认值0表示主对角线，负值表示低对角线，正值表示高对角线。
dtype：数组元素的数据类型，可选项，默认numpy.float64
"""
print("np.eye\n",np.eye(4,5,-1))#主对角线为1的数组,第三位可以让对角线向上向下移动
print()

"""

numpy.diag(v, k=0)

v：array_like 如果v是二维数组，返回k位置的对角线。 如果v是一维数组，返回一个v作为k位置对角线的二维数组。
k：int, optional 默认为0，可选参数。 指定对角线的位置，大于零位于对角线上面，小于零则在下面。
"""
print("np.diag([一维数组的对角线])\n",np.diag([1,2,3,4],2)),#指定一维数组对角线的值,并且用k设置对角线位置
print("np.diag([二维数组的对角线位置])\n",np.diag([[1,2],[3,4]])),#指定二维数组对角线的位置
print()

"""
numpy.ones(shape，dtype)
shape: tuple类型 指定要创建数组的形状
用于创建元素全部为1的数组，即创建的数组元素全部填充为1
"""
print("np.ones((2,3))\n",np.ones((2,3)))#1填充数组
print()
"""
numpy.zeros(shape，dtype)
创建的数组元素全部填充为0
"""
print("np.zeros(5,dtype=int)",np.zeros(5,dtype=int))#0填充数组
print("zeros()\n",np.zeros((2, 3)))
print()



[   0   -5  -10  -15  -20  -25  -30  -35  -40  -45  -50  -55  -60  -65
  -70  -75  -80  -85  -90  -95 -100]
[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
[1.000e+00 2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01 6.400e+01
 1.280e+02 2.560e+02 5.120e+02 1.024e+03]
np.identit
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

np.eye
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

np.diag([一维数组的对角线])
 [[0 0 1 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 4]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
np.diag([二维数组的对角线位置])
 [1 4]

np.ones((2,3))
 [[1. 1. 1.]
 [1. 1. 1.]]

np.zeros(5,dtype=int) [0 0 0 0 0]
zeros()
 [[0. 0. 0.]
 [0. 0. 0.]]

np.empty((2,5))
 [[            nan 0.00000000e+000 9.62588513e-312 2.02369289e-320
  0.00000000e+000]
 [0

In [85]:
import numpy as np
# 对于NumPy，与随机数相关的函数都在random模块中，其中包括了可以生成服从多种概率分布随机数的函数。

"""
numpy.empty(shape，dtype)
创建指定形状的随机数
"""
print("np.empty((2,5))\n",np.empty((2,5)))
print()

"""
numpy.random.random(size=None)
random函数是最常见的生成随机数的方法

其中参数size指定数组的shape，tuple类型，默认None。

数组元素的值随机生成，范围：[0,1)。
"""
print("np.random.random((5,5))\n",np.random.random((5,5)))#生成形状的随机数
print()


"""
numpy.random.rand(dn)函数
rand()函数隶属于numpy.random模块，它的作用是随机生成N维浮点数组。

random.rand(d0, d1, ..., dn)

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

根据指定的shape创建一个数组；数组元素的值随机生成，范围：[0,1)。

其中参数指定了数组的shape，int型。
"""

print("np.random.rand(2,2)\n",np.random.rand(2,2))#生成的随机浮点数
print()


"""
numpy.random.random_sample(size=None)
生成一个[0,1)之间随机浮点数或N维浮点数组。
"""
print("np.random.random_sample(size=5)\n",np.random.random_sample(size=5))
print()
"""
numpy.random.randint()函数生成一个整数或N维整数数组。

randint(low, high=None, size=None, dtype=None)

low：int or array-like of ints 必须参数，如果只有参数low，则生成数值范围是[0,low)，要求low>0。

high：int or array-like of ints, optional 可空。如果有参数high，则生成数值范围是 [low,high)，要求low<high。
size：int or tuple of ints, optional 指定生成的随机数或数组的shape。
dtype：dtype, optional 指定生成随机数的数据类型（整数类型的位长）。

"""
print("numpy.random.randint(min:3,max:8,size:10)\n",np.random.randint(3,8,10))#函数生成一个整数或N维整数数组。
print()

"""
numpy.random.random_integers()函数
numpy.random.random_integers()函数生成一个整数或一个N维整数数组。

numpy.random.random_integers(low, high=None, size=None)：

参数： 若high不为None，则取[low,high]之间随机整数，否则取[1,low]之间随机整数。
"""
print("numpy.random.random_integers(min:1,max:10,size:30)\n",np.random.random_integers(1,10,30)) #生成左闭右闭的随机
print()

"""
函数
numpy.random.choice()函数从序列中获取元素。

numpy.random.choice(a, size=None, replace=True, p=None)

a：若a为整数，元素取值为np.range(a)中随机数；若a为一维数据，取值为a中随机元素。
size：指定生成的随机数或数组的shape。

"""
print("np.random.choice\n",np.random.choice((1,-1),1001))#从给定序列中随机选择
print()


"""
numpy.random.randn()函数
numpy.random.randn()函数生成一个浮点数或N维浮点数组，符合正态分布的随机样本数。

numpy.random.randn(d0, d1, ..., dn)：

参数指定生成数组的shape，int型。"""

print(f"numpy.random.randn(){np.random.randn(10)}")#符合正态分布的随机
print()
"""
随机数生成器 seed
np.random.seed(n)


n ： 种子编号
种子相同,则生成规则相同
"""
np.random.seed(10)
print(np.random.randn(5))
np.random.seed(10)
print(np.random.randn(5))


"""
asarray()函数,把列表转换为数组
np.asarray(data,dtype=None,order=None)

参数 data： 类数组数据
返回值：新数组
"""
data1=([0,1,2],[3,4,5],[6,7,8])
arr=np.asarray(data1)
print(arr)

np.empty((2,5))
 [[-0.20276354 -0.83432699  0.83631669  1.30363914 -0.8126403 ]
 [-0.74285337  1.12293834 -0.01288006  1.3157235   0.69310824]]

np.random.random((5,5))
 [[0.49850701 0.22479665 0.19806286 0.76053071 0.16911084]
 [0.08833981 0.68535982 0.95339335 0.00394827 0.51219226]
 [0.81262096 0.61252607 0.72175532 0.29187607 0.91777412]
 [0.71457578 0.54254437 0.14217005 0.37334076 0.67413362]
 [0.44183317 0.43401399 0.61776698 0.51313824 0.65039718]]

np.random.rand(2,2)
 [[0.60103895 0.8052232 ]
 [0.52164715 0.90864888]]

np.random.random_sample(size=5)
 [0.31923609 0.09045935 0.30070006 0.11398436 0.82868133]

numpy.random.randint(min:3,max:8,size:10)
 [6 7 4 7 5 3 3 7 7 3]

numpy.random.random_integers(min:1,max:10,size:30)
 [ 9  3  7  3  9  9  7  7  6  7  1  1  7 10  2  9 10  2  3  9 10 10  6  1
  3  8  4  1  5  3]

np.random.choice
 [ 1  1 -1 ...  1 -1 -1]

numpy.random.randn()[ 0.71527897 -0.20276354 -0.83432699  0.83631669  1.30363914 -0.8126403
 -0.74285337  1.12293834 -0

C:\Users\Spark\AppData\Local\Temp/ipykernel_11428/1695071932.py:69: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  print("numpy.random.random_integers(min:1,max:10,size:30)\n",np.random.random_integers(1,10,30)) #生成左闭右闭的随机


In [39]:
import numpy as np
# 数组基本操作

"""
asarray()函数,把列表转换为数组
np.asarray(data,dtype=None,order=None)

参数 data： 类数组数据
返回值：新数组
"""
data1=([0,1,2],[3,4,5],[6,7,8])
arr=np.asarray(data1)



arr=np.arange(24)
print(arr)

arr1=arr.astype("float")
print(arr1)
print("================================================================")





"""
1 转换数组元素的数据类型
arr.astype(dtype)
dtype: 指定新的数据类型
注意，要保证原始数组中的每个元素都能转换成指定的新数据类型
"""
# 1
arr2=arr1.astype("U")
print(arr2)
# 2
arr3=arr2.astype("float")
print(arr3)
# 3 浮点字符串无法转换为整型
# arr4=arr2.astype("int")
# print(arr4)
print("*************************************")
"""
改变数组的形状 shape
(1) arr.shape=newShape
改变数组对象的shape属性值（Tuple）
注意，数组的元素个数（size）不能变
"""
print(arr)
# arr.shape(3,8)
arr.shape=(3,8)
print("用shap修改形状\n",arr)

print("--------------------------------------------------")
"""
arr.reshape(shape)函数
参数shape：指定新形状
返回值：返回新数组，不改变原始数组的形状
注意： 数组元素个数（size）不变
"""
arr=np.arange(24)
print("arr.shape=",arr.shape)
arr2=arr.reshape(2,3,4)
print("reshape...不修改原数组,改变数组后需要有变量接收")
print("arr.shape=",arr.shape)
print("arr2.shape=",arr2.shape)


print("=====================resize()============================")
"""
改变数组长度 resize（shape）
注意：1 数组.size 属性是只读属性 不允许修改
参数shape：指定新的形状
数组size如果变小，按照顺序，保留前面的元素
数组size如果变大，在原始数组元素后面补充元素值，数值型补0，字符串补‘’空串

"""
arr=np.arange(24)
print("arr.size",arr.size)
arr.resize((3,12))
print("arr.resize((3,12))\n",arr)
arr.resize((12),refcheck=True)
print("arr.resize((12))\n",arr)

print("===============numpy.resize(arr，shape)====================")
"""
（2）numpy.resize(arr，shape)
返回新数组，不改变原始数组

参数arr：原始数组
参数shape：指定新的形状
数组size如果变小，按照顺序，保留前面的元素
数组size如果变大，在原始数组元素后面补充元素值，数值型补0，字符串补‘’空串
"""
a0=np.arange(12).reshape(3,4)

# 在a0基础上创建a1， a1是0-9 的一维数组
a1=np.resize(a0,(10))
a1
# 在a1基础上创建a2， a2的形状 （2,2,3）
a2=np.resize(a1,(2,2,3))
a2
      

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]
['0.0' '1.0' '2.0' '3.0' '4.0' '5.0' '6.0' '7.0' '8.0' '9.0' '10.0' '11.0'
 '12.0' '13.0' '14.0' '15.0' '16.0' '17.0' '18.0' '19.0' '20.0' '21.0'
 '22.0' '23.0']
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]
*************************************
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
用shap修改形状
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
--------------------------------------------------
arr.shape= (24,)
reshape...不修改原数组,改变数组后需要有变量接收
arr.shape= (24,)
arr2.shape= (2, 3, 4)
=====================resize()============================
arr.size 24
arr.resize((3,12))
 [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]]
arr.resize((12))

array([[[0, 1, 2],
        [3, 4, 5]],

       [[6, 7, 8],
        [9, 0, 1]]])

In [55]:
#数组高级操作
import numpy as np
"""
数组展平
将多维数组变成一维

(1) arr.ravel() / np.ravel(arr)
(2) arr.flatten()
返回新数组，原始数组不变
"""
#数组展平
arr2=np.arange(12).reshape(3,4)
print(arr2)
print("数组展平ravel:",arr2.ravel())
print("数组竖着展平flatten::",arr2.flatten("F"))
print("数组横着展平flatten::",arr2.flatten())

"""
5 数组重复
(1) tile（）函数
将数组元素在各个轴方向上按指定次数重复，返回新数组，原始数组不变。

numpy.tile(arr,reps)
参数 arr： 原始数组
参数 reps 指定重复的次数和方向（轴）从左到右分别为0,1,2......
返回新数组
"""
arr=np.arange(6).reshape(2,3)
print(arr)

arr2=np.tile(arr,2)

print(arr2)

arr2=np.tile(arr,[2,3])

print(arr2)
arr2=np.tile(arr,[2,3,4])

print(arr2)

print("=============np.repeat(arr,reps,axis=None)=====================")
"""
将数组元素在各个轴方向上按指定次数重复，返回新数组，原始数组不变。

np.repeat(arr,reps,axis=None)
参数 arr： 原始数组
参数 reps： 指定重复的次数
参数 axis：指定重复的方向（轴）
返回新数组
"""
arr=np.arange(24).reshape(2,3,4)
print(arr)
arr2=np.repeat(arr,2,0)#0轴重复2次
print("#0轴重复2次")
print(arr2)
arr2=np.repeat(arr,2,1)#1轴重复2次
print("#1轴重复2次")
print(arr2)
arr2=np.repeat(arr,2,2)#2轴重复2次
print("#2轴重复2次")
print(arr2)



print("===========numpy.concatenate（）============")
# #数组组合
"""
6 数组的连接组合
将各数组元素在指定轴方向上组合。
拆开在组合,最后维度不变
np.concatenate(arrs,axis)
参数 arrs： 准备组合的各原始数组
参数 axis： 指定轴方向
返回新数组
"""
arr3=np.arange(24).reshape(2,3,4)
arr4=arr3*-1
arr5=arr3*0
print("原数组arr3和arr4,arr5分别为:\n",arr3,"\n\n",arr4,"\n\n",arr5)
print("0轴(z向)组合为:\n",np.concatenate((arr3,arr4,arr5),axis=0))
print("1轴(y向)组合为:\n",np.concatenate((arr3,arr4,arr5),axis=1))
print("2轴(x向)组合为:\n",np.concatenate((arr3,arr4,arr5),axis=2))

print("==================numpy.stack()==================")
"""
将各数组元素在指定轴方向上组合。
作为整体组合,最后维度+1
np.stack(arrs,axis)
参数 arrs： 准备组合的各原始数组
参数 axis： 指定轴方向
返回新数组
"""
arr3=np.arange(24).reshape(2,3,4)
arr4=arr3*-1
arr5=arr3*0
print("原数组arr3和arr4,arr5分别为:\n",arr3,"\n\n",arr4,"\n\n",arr5)
print("0轴(z向)组合为:\n",np.stack((arr3,arr4,arr5),axis=0))
print("1轴(y向)组合为:\n",np.stack((arr3,arr4,arr5),axis=1))
print("2轴(x向)组合为:\n",np.stack((arr3,arr4,arr5),axis=2))

                          
print("================= numpy.hstack（）与numpy.vstack（）=====================")
"""
(3) numpy.hstack（）函数
将各数组元素横向（第1轴）组合。

np.hstack(arrs)
参数 arrs： 准备组合的各原始数组
返回新数组
(4) numpy.vstack（）函数
将各数组元素纵向（第0轴）组合。

np.vstack(arrs)
参数 arrs： 准备组合的各原始数组
返回新数组
"""
arr3=np.arange(24).reshape(2,3,4)
arr4=arr3*-1
arr5=arr3*0
print("原数组arr3和arr4,arr5分别为:\n",arr3,"\n\n",arr4,"\n\n",arr5)
print("0轴(z向)组合为:\n",np.vstack((arr3,arr4,arr5)))
print("1轴(y向)组合为:\n",np.hstack((arr3,arr4,arr5)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
数组展平ravel: [ 0  1  2  3  4  5  6  7  8  9 10 11]
数组竖着展平flatten:: [ 0  4  8  1  5  9  2  6 10  3  7 11]
数组横着展平flatten:: [ 0  1  2  3  4  5  6  7  8  9 10 11]
[[0 1 2]
 [3 4 5]]
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]]
[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]
 [0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]]
[[[0 1 2 0 1 2 0 1 2 0 1 2]
  [3 4 5 3 4 5 3 4 5 3 4 5]
  [0 1 2 0 1 2 0 1 2 0 1 2]
  [3 4 5 3 4 5 3 4 5 3 4 5]
  [0 1 2 0 1 2 0 1 2 0 1 2]
  [3 4 5 3 4 5 3 4 5 3 4 5]]

 [[0 1 2 0 1 2 0 1 2 0 1 2]
  [3 4 5 3 4 5 3 4 5 3 4 5]
  [0 1 2 0 1 2 0 1 2 0 1 2]
  [3 4 5 3 4 5 3 4 5 3 4 5]
  [0 1 2 0 1 2 0 1 2 0 1 2]
  [3 4 5 3 4 5 3 4 5 3 4 5]]]
=============np.repeat(arr,reps,axis=None)=====================
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
#0轴重复2次
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]



# 课后作业

In [36]:
import numpy as np
#创建三维数组
arr=np.array((1,2,3,4,5,6),ndmin=4).reshape((3,1,2))
# arr=np.arange(1,7).reshape((1,2,3))#分别为面,行,列
print(arr)

[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [4]:
#创建2,4,8,16....1024
import numpy as np
print(np.logspace(0,10,11,base=2.0,dtype=int))

[   1    2    4    8   16   32   64  128  256  512 1024]


In [4]:
"""
# 有一酒鬼 最初的位置  是原点 

# 该酒鬼走了2000步，方向不定(要么前进，要么后退，在一条直线上)，步长  0.5  米  

# 问 2000步中   该 酒鬼距离 原点的最远距离是多少 

# 以及距离原点最远时 他走了多少步  
"""
import numpy as np

# 随机生成前进或后退
step=np.random.choice((0.5,-0.5),2000)
#初始化现在位置,最大距离步数,最大距离,方向
now=0
maxStep=0
maxDistance=0
direction=""
#走走退退,并获取最大距离和最大距离是走了多少步
for i in range(len(step)):
    now+=step[i]
    if abs(maxDistance)< abs(now):
        maxDistance=now
        maxStep=i
#判断在向前走还是向后走
direction="前进" if maxDistance>0 else "后退"
#打印输出
print(f"最远距离为:{direction}{abs(maxDistance)}米")
print(f"最远距离他走了:{maxStep}步")


最远距离为:后退17.5米
最远距离他走了:640步
